- doc/storyboard_draft.md
This should cover all the given requirements. Now we just need to worry about implementing them.
> Add Habit Events and Social to storyboard

- app/src/main/java/com/github/cmput301f21t44/hellohabits/db/HabitDao.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/db/HabitEntity.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/db/HabitEntityRepository.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/model/Habit.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/model/HabitRepository.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/view/ViewHabitFragment.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/viewmodel/HabitViewModel.java
- app/src/main/res/layout/fragment_view_habit.xml
Instead of directly modifying the Habit, we just copy it to the fragment
and then update the database using an @Update DAO method.
We also removed the  observe call from the save Habit button listener
because we don't want to overwrite the text everytime it's updated
externally.
Closes #4.
> Feature: Update Habit

- app/src/main/java/com/github/cmput301f21t44/hellohabits/db/AppDatabase.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/db/habit/HabitEntity.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/db/habit/HabitWithEvents.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/db/habitevent/EmbeddedLocation.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/db/habitevent/HabitEventEntity.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/db/habitevent/HabitEventEntityRepository.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/model/Habit.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/view/habit/DatePickerFragment.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/view/habitevent/CreateEditHabitEventFragment.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/viewmodel/HabitEventViewModel.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/viewmodel/HabitViewModel.java
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/fragment_all_habits.xml
- app/src/main/res/layout/fragment_create_edit_habit_event.xml
- app/src/main/res/layout/habit_item.xml
- app/src/main/res/layout/list_habit_item.xml
- app/src/main/res/navigation/nav_graph.xml
- app/src/main/res/values/strings.xml
Add the delete button when editing a habit event
Closes #21.
> Feature: Delete Habit Event Button

- app/src/main/java/com/github/cmput301f21t44/hellohabits/view/habit/AllHabitsFragment.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/view/habit/HabitAdapter.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/view/habit/TodaysHabitsFragment.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/view/habit/ViewHabitFragment.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/view/habitevent/CreateEditHabitEventFragment.java
- app/src/main/res/layout/fragment_create_edit_habit_event.xml
There were some spots where the list fragment ID wasn't selected.
Also removed unnecessary back button from create/edit habit event.
We're probably not going to do the photo thing for now. Having no access
to a real Android device is making it difficult. I think Kynan should be
the one to do this, just because he has an Android device with a real
camera.
> Fix navigation from habit list

- app/src/main/java/com/github/cmput301f21t44/hellohabits/firebase/Authentication.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/firebase/FSHabit.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/firebase/FSHabitEvent.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/firebase/FirebaseTask.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/firebase/FirestoreEventRepository.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/firebase/FirestoreHabitRepository.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/firebase/FirestoreRepository.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/model/HabitEventRepository.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/model/HabitRepository.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/view/habit/CreateEditHabitFragment.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/view/habit/TodaysHabitsFragment.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/view/habit/ViewHabitFragment.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/view/habitevent/CreateEditHabitEventFragment.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/viewmodel/HabitEventViewModel.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/viewmodel/HabitViewModel.java
Added callbacks for Firebase operations. It looks like a mess right now
but at least successes and failures are handled properly. Not sure how
this will be tested, though.
Closes #62.
> Fix: Add success and failure callbacks

- app/src/main/java/com/github/cmput301f21t44/hellohabits/firebase/Authentication.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/firebase/FSHabit.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/firebase/FSHabitEvent.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/firebase/FirebaseTask.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/firebase/FirestoreEventRepository.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/firebase/FirestoreHabitRepository.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/firebase/FirestoreRepository.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/model/HabitEventRepository.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/model/HabitRepository.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/view/MainActivity.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/view/habit/AllHabitsFragment.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/view/habit/CreateEditHabitFragment.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/view/habit/DatePickerFragment.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/view/habit/DaysOfWeekFragment.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/view/habit/HabitAdapter.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/view/habit/TodaysHabitsFragment.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/view/habit/ViewHabitFragment.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/view/habitevent/CreateEditHabitEventFragment.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/view/habitevent/HabitEventAdapter.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/view/social/LoginFragment.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/viewmodel/HabitEventViewModel.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/viewmodel/HabitViewModel.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/viewmodel/PreviousListViewModel.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/viewmodel/ViewModelFactory.java
!!! Make sure to merge #68 first !!!
Refactor code to follow the following Android style guide:
https://source.android.com/setup/contribute/code-style
- Add the prefix `m` to private members, `s` for static members, and
ALL_CAPS_SNAKE_CASE for constants
- Limit line width to 100
- Limit method length to 40 lines
Also, nice.
> Refactor: Follow style guide

- .idea/deploymentTargetDropDown.xml
- app/build.gradle
- app/src/main/java/com/github/cmput301f21t44/hellohabits/firebase/Authentication.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/model/DaysOfWeek.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/model/HabitEventRepository.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/model/HabitRepository.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/model/Location.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/view/InputValidator.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/view/OnItemClickListener.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/view/habit/AllHabitsFragment.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/view/habit/CreateEditHabitFragment.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/view/habit/DatePickerFragment.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/view/habit/DaysOfWeekFragment.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/view/habit/HabitAdapter.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/view/habit/TodaysHabitsFragment.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/view/habit/ViewHabitFragment.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/view/habitevent/CreateEditHabitEventFragment.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/view/habitevent/HabitEventAdapter.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/view/social/LoginFragment.java
Most functions in model and view has complete comments now
Except:
View:
AllHabitsFragment:
onCreateView()
onViewCreated()
DaysOfWeekFragment:
newInstance()
OnConfirmCallback()
HabitAdapter:
almost all functions
TodaysHabitsFragment:
onViewCreated()
HabitEventAdapter:
all functions
MainActivity:
all functions
> add comments to functions in model and view

- .firebaserc
- .gitignore
- app/build.gradle
- app/src/androidTest/java/com/github/cmput301f21t44/hellohabits/HabitEventTest.java
- app/src/androidTest/java/com/github/cmput301f21t44/hellohabits/HabitTest.java
- app/src/androidTest/java/com/github/cmput301f21t44/hellohabits/IntentTestSuite.java
- app/src/androidTest/java/com/github/cmput301f21t44/hellohabits/LoginTest.java
- app/src/androidTest/java/com/github/cmput301f21t44/hellohabits/TestUtil.java
- app/src/main/AndroidManifest.xml
- firebase.json
Do testing on Login, Habit, and Habit Event.
One caveat is that the Login tests have to be done first.
Habit and Habit Event need a valid account to run.
Closes #46 
Closes #48
> Test: Intent testing

- app/src/main/java/com/github/cmput301f21t44/hellohabits/model/DaysOfWeek.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/model/Habit.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/model/HabitEvent.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/model/HabitEventRepository.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/model/HabitRepository.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/model/Location.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/view/habit/AllHabitsFragment.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/view/habit/CreateEditHabitFragment.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/view/habit/DatePickerFragment.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/view/habit/DaysOfWeekFragment.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/view/habit/HabitAdapter.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/view/habit/TodaysHabitsFragment.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/view/habit/ViewHabitFragment.java
added comments for each class header
> added class comment headers

- app/src/main/java/com/github/cmput301f21t44/hellohabits/firebase/FirestoreRepository.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/model/Habit.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/view/habit/TodaysHabitsFragment.java
This is done by destroying all fragments and then restarting the MainActivity. Also added a dialog when logging out since that's kind of a big deal.
To make things easier for us when finishing up this project, I suggest everyone to document your own code. This is so that we don't have to worry about assigning documentation to anyone in the future (no more guessing what other people's code does!).
Closes #83.
> Fix: Data inconsistency when logging out

- app/src/androidTest/java/com/github/cmput301f21t44/hellohabits/ExampleInstrumentedTest.java
- app/src/androidTest/java/com/github/cmput301f21t44/hellohabits/HabitEventTest.java
- app/src/androidTest/java/com/github/cmput301f21t44/hellohabits/HabitTest.java
- app/src/androidTest/java/com/github/cmput301f21t44/hellohabits/LoginTest.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/firebase/FSHabit.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/firebase/FSHabitEvent.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/firebase/FirestoreHabitRepository.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/model/Habit.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/model/HabitRepository.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/view/habit/CreateEditHabitFragment.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/view/habit/HabitAdapter.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/view/habit/ViewHabitFragment.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/viewmodel/HabitViewModel.java
- app/src/main/res/drawable/ic_baseline_lock_24.xml
- app/src/main/res/layout/fragment_create_edit_habit.xml
- app/src/main/res/layout/fragment_view_habit.xml
- app/src/main/res/layout/list_habit_event_item.xml
- app/src/main/res/layout/list_habit_item.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/com/github/cmput301f21t44/hellohabits/ExampleUnitTest.java
- app/src/test/java/com/github/cmput301f21t44/hellohabits/HabitViewModelTest.java
- Added a little icon to display whether a habit is private or not
- Formatted files
Closes #1.
> Feature: Add visibility option to Habits

- .idea/deploymentTargetDropDown.xml
- app/src/main/java/com/github/cmput301f21t44/hellohabits/viewmodel/PreviousListViewModel.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/viewmodel/ViewModelFactory.java
- app/src/test/java/com/github/cmput301f21t44/hellohabits/PreviousListViewModelTest.java
- app/src/test/java/com/github/cmput301f21t44/hellohabits/ViewModelFactoryTest.java
- settings.gradle
`ViewModelFactory` is a pretty unique class, no need to worry about the `ViewModelFactoryTest`.
We can add tests similar to the one in`PreviousListViewModelTest` to test `HabitEventViewModel`'s and `HabitViewModel`'s `selected` members. I thought that mocking would be needed for that but apparently not.
> Testing: PreviousListViewModel and ViewModelFactory

- app/src/main/java/com/github/cmput301f21t44/hellohabits/firebase/FSFollow.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/firebase/FSUser.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/firebase/FirestoreUserRepository.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/firebase/UserMapLiveData.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/model/social/UserRepository.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/view/habit/HabitListFragment.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/view/social/LoginFragment.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/view/social/UserAdapter.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/view/social/UserListFragment.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/viewmodel/PreviousListViewModel.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/viewmodel/UserViewModel.java
- app/src/main/res/layout/fragment_create_edit_habit.xml
- app/src/main/res/layout/fragment_habit_list.xml
- app/src/main/res/layout/list_user_item.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/com/github/cmput301f21t44/hellohabits/UserViewModelTest.java
Closes #96. I still need help on fixing the habit consistency
> Fix: User Live data issues

- app/src/main/java/com/github/cmput301f21t44/hellohabits/firebase/FirestoreHabitRepository.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/firebase/FirestoreRepository.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/firebase/HabitMapLiveData.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/model/habit/Habit.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/view/habit/AllHabitsFragment.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/view/habit/HabitAdapter.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/view/habit/HabitListFragment.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/view/habit/TodaysHabitsFragment.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/view/habit/UserHabitListFragment.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/viewmodel/HabitViewModel.java
At what cost? Breaking the design lmao
Closes #95
> Fix Habit Event consistency issues

- doc/final_storyboard.md
I tried anticipating the screens for the unfinished features, but we
might still have to change some things.
Related to #99 but doesn't close.
> Doc: Start on final storyboard

- app/src/androidTest/java/com/github/cmput301f21t44/hellohabits/HabitEventTest.java
- app/src/androidTest/java/com/github/cmput301f21t44/hellohabits/TestUtil.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/firebase/FirestoreHabitRepository.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/firebase/UserMapLiveData.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/model/habit/DaysOfWeek.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/model/habit/Habit.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/view/habit/HabitAdapter.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/view/habit/HabitListFragment.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/viewmodel/HabitViewModel.java
- app/src/test/java/com/github/cmput301f21t44/hellohabits/DaysOfWeekTest.java
> Remove debug Logs

- app/src/main/java/com/github/cmput301f21t44/hellohabits/view/social/UserAdapter.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/view/social/UserListFragment.java
> Add Toast messages when UserViewModel fails

- app/src/main/java/com/github/cmput301f21t44/hellohabits/firebase/FSUser.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/firebase/FirestoreUserRepository.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/model/social/UserRepository.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/view/MainActivity.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/view/habit/AllHabitsFragment.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/view/habit/TodaysHabitsFragment.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/viewmodel/UserViewModel.java
- app/src/main/res/layout/fragment_create_edit_habit.xml
- app/src/main/res/layout/fragment_create_edit_habit_event.xml
- app/src/main/res/layout/fragment_view_habit.xml
- app/src/main/res/layout/nav_header_main.xml
Also removed fixed dimensions on some elements. Make sure to use "wrap_content" on elements so that no text is cut out.
> Add "Hello, {name}" on sidebar

- app/src/main/java/com/github/cmput301f21t44/hellohabits/firebase/FirestoreUserRepository.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/view/MainActivity.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/view/habit/TodaysHabitsFragment.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/view/social/LoginFragment.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/viewmodel/UserViewModel.java
- app/src/main/res/layout/fragment_login.xml
- app/src/main/res/values/strings.xml
> Save login credentials

- app/src/androidTest/java/com/github/cmput301f21t44/hellohabits/FollowTest.java
- app/src/androidTest/java/com/github/cmput301f21t44/hellohabits/FollowerTest.java
- app/src/androidTest/java/com/github/cmput301f21t44/hellohabits/HabitEventTest.java
- app/src/androidTest/java/com/github/cmput301f21t44/hellohabits/HabitReorderTest.java
- app/src/androidTest/java/com/github/cmput301f21t44/hellohabits/HabitTest.java
- app/src/androidTest/java/com/github/cmput301f21t44/hellohabits/LoginTest.java
- app/src/androidTest/java/com/github/cmput301f21t44/hellohabits/SocialTest.java
- app/src/androidTest/java/com/github/cmput301f21t44/hellohabits/TestUtil.java
- app/src/androidTest/java/com/github/cmput301f21t44/hellohabits/ViewUserHabitsTest.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/firebase/FirestoreHabitRepository.java
- app/src/main/java/com/github/cmput301f21t44/hellohabits/firebase/FirestoreUserRepository.java
- app/src/test/java/com/github/cmput301f21t44/hellohabits/viewmodel/UserViewModelTest.java
Also moved the Habit Reorder test to its own class as it's already pretty complicated on its own.
Broke down classes for different `@BeforeClass` and `@AfterClass` methods
Part of #101.
> Testing: Intent tests on Following/Followers
